### ISSUE TITLE
Add timestamp value to the result of /events/stream/*

### ISSUE THREAD

**Issue by PerhunAndrey** [SubKit/subkit-microservice#54]
Now we receive events without information about its timestamp as we do when retrieving history of persistent events.

**Comment by MikeBild** [comment]
added by [29b1d68](https://github.com/SubKit/subkit-microservice/commit/29b1d68798ea7cf3b592773a7cd046bbfb195887)

**Comment by PerhunAndrey** [comment]
tests is ok 8f021f9
