### ISSUE TITLE
Subscribe to event streams with filter /events/stream does not work

### ISSUE THREAD

**Issue by PerhunAndrey** [SubKit/subkit-microservice#57]
1. look at describe('Subscribe to event streams with filter (Transfer-Encoding: chunked)' on  4cd2eedd
2. I propose o rename route to /events/streams

**Comment by MikeBild** [comment]
fixed tests by 
[60db80874bda55d29e89d5dd023ef96d4d06f8cd](https://github.com/SubKit/subkit-microservice/commit/60db80874bda55d29e89d5dd023ef96d4d06f8cd)

**Comment by MikeBild** [comment]
2.
GET /events/streams is a route to get all available stream. Why do you think it would be better?

**Comment by PerhunAndrey** [comment]
Oh, yes. I've forgot overlook it.
