### ISSUE TITLE
Make tests cases more readable

### ISSUE THREAD

**Issue by MikeBild** [SubKit/subkit-microservice#58]
The test construction are highly nested. We should try to improve by refactor to some test helper functions.

**Comment by PerhunAndrey** [comment]
In some cases we cannot guarantee coming of events in desired order or ordering of events' emission is the only way to test. What do you think?

**Comment by MikeBild** [comment]
yes, thats right. We can use a promise library like Q to reduce nested calls.

**Comment by PerhunAndrey** [comment]
I prefer Bluebird

**Comment by MikeBild** [comment]
https://www.npmjs.com/package/superagent-promise

**Comment by MikeBild** [comment]
or request + request-promise (i like, because it has support for streams)

https://www.npmjs.com/package/request
https://www.npmjs.com/package/request-promise

**Comment by PerhunAndrey** [comment]
superagent supports piping too http://visionmedia.github.io/superagent/#piping-data
so I will use superagent-promise - it will take less time to rewrite existsing tests.

**Comment by MikeBild** [comment]
sounds good

**Comment by PerhunAndrey** [comment]
and I see you removed promises? but you said earlier that you want to rid of nesting... So do I need to think about another approach ?

**Comment by PerhunAndrey** [comment]
Should we rewrite tests using async.waterfall as it is done on tasks.spec.js?https://github.com/SubKit/subkit-microservice/blob/master/test/integration/task.spec.js#L61

Or maybe that issue is not necessary now?

**Comment by MikeBild** [comment]
Yes, the spec file looks very readable.
