### ISSUE TITLE
Complex queries does not work on /events/stream

### ISSUE THREAD

**Issue by PerhunAndrey** [SubKit/subkit-microservice#61]
look at it('Should receive all messages where matching JSONQuery `{$and: [{stream: \'A-Stream\'}, {"$payload.Number": 2}]}` and window size = 2' on  97eeb66a

**Comment by MikeBild** [comment]
fix with [82c915679d2682bc9602447d5f648e34c2d4a1ac](https://github.com/SubKit/subkit-microservice/commit/82c915679d2682bc9602447d5f648e34c2d4a1ac)

Note: remove the `$` sign in filters, it's a syntax change in comparison to store filters.

**Comment by PerhunAndrey** [comment]
fixed with 55828bc034a8d73fcc14ceb678d69334cfae0d83
