### ISSUE TITLE
Subscription on events with wilter that include Persistent field doe not works

### ISSUE THREAD

**Issue by PerhunAndrey** [SubKit/subkit-microservice#62]
look on it('Should receive all persistent messages where matching JSONQuery `{$and: [{stream: \'A-Stream\'}, {"payload.Number": 2}]}` and window size = 2' at 4defe97896c3b049053b07ed35ac45f52ca42bb5

**Comment by MikeBild** [comment]
Persistent events are events that additionally stored in the storage. E.g. you can emit events without "active" subscribers. All emitted events are stored in local storage and can be get via /events/history/myStreamName for later processing or analysis.

**Comment by PerhunAndrey** [comment]
So event cannot be emitted if there is no one listener for it's stream?
Can one listener received an event emitted within a stream from emitent with another auth token?

**Comment by MikeBild** [comment]
"So event cannot be emitted if there is no one listener for it's stream?"
An emitted event is always emitted. With or without listener.

Can one listener received an event emitted within a stream from emitent with another auth token?
Yes, it theory. At this moment we habe only one auth token.

**Comment by MikeBild** [comment]
Done?

**Comment by PerhunAndrey** [comment]
test which correspond to issue is skipped and does not run (timeout)

**Comment by MikeBild** [comment]
done with ac55b07ec77edb57700ac46a074c637c5142f494

**Comment by PerhunAndrey** [comment]
You have rewrite test for it.skip('Should receive all persistent
as if it is a test not for persistent events
So you mean that persistent flag may not be included in filter?

**Comment by MikeBild** [comment]
done?

**Comment by PerhunAndrey** [comment]
You've change the test     it('Should receive all persistent messages where matching JSONQuery `{$and: [{stream: \'B-Stream\'}, {"payload.Number": 2}]}` and window size = 2', function (done) {

**Comment by MikeBild** [comment]
dix 35714b267bdcc6b577f5a094f488fc1c26813ff2
