### ISSUE TITLE
Strange behaviour of emit an event 

### ISSUE THREAD

**Issue by PerhunAndrey** [SubKit/subkit-microservice#63]
Look at 4defe97896c3b049053b07ed35ac45f52ca42bb5
Strange behaviour of 
it('It should emit an event within `news` stream'
and 
it('It should emit an event within `news` stream'

When they runed alone - all is ok
When they runed with other test cases - they failed.

**Comment by MikeBild** [comment]
look "how persistent events and event-history works" at my last commit

[a21a59a61f65e](https://github.com/SubKit/subkit-microservice/commit/a21a59a61f65eaf38ce9e833c658a89b8cd904e6#diff-30fd31512657d20242e2be233628c043R1076)
