### ISSUE TITLE
/manage/log:name should send log not as part of responce but as a file

### ISSUE THREAD

**Issue by PerhunAndrey** [SubKit/subkit-microservice#66]
see https://github.com/SubKit/subkit-microservice/blob/master/routes/manage.js#L126
there you send log via res.send but size of log file may be too large to fit into http response.

**Comment by PerhunAndrey** [comment]
.

**Comment by MikeBild** [comment]
Is that issue solved?

**Comment by PerhunAndrey** [comment]
Not. You send log as a body. And also you load whole log into memory and in case of very large log potentially you can receive "out of memory". I propose to send/receive logs and import/export files as a stream.

**Comment by MikeBild** [comment]
done with ad663df07cf838b2daf1a442f637459505bd93f1
