### ISSUE TITLE
Get Process-Log-File and Subscribe to Log-Stream does not work

### ISSUE THREAD

**Issue by PerhunAndrey** [SubKit/subkit-microservice#67]
see tests in manage.spec.js on 10bb91ec

**Comment by MikeBild** [comment]
Is that issue solved?

**Comment by PerhunAndrey** [comment]
1. On 'Get Process-Log-File' I receive 200 but with empty body. And there not /logs dir in /files dir.

**Comment by PerhunAndrey** [comment]
2. 'Subscribe to Log-Stream' works.

**Comment by MikeBild** [comment]
Isn't a log file present, you receive a 200 with a empty body, because it should be idempotent.

**Comment by MikeBild** [comment]
done with 3b2d239cefc53bcded28a9898bc145af58e42be0
